services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  server:
    build: 
      dockerfile: ./apps/solar-monitor/Dockerfile
      context: .
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8080:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana-storage:
